### ISSUE TITLE
Urls returning a 404 - poss routing issue

### ISSUE THREAD

**Issue by Alex-Rafter** [cal-dev-lab/baunk-agency-reactjs#2]
Urls are returning a 404 e.g
[https://baunk-agency.netlify.app/category/fashion](https://baunk-agency.netlify.app/category/fashion)

Wondering if this might be due to routing.
This could possibly be helpful / might point you in the right direction if it is?
[https://oliverjam.es/blog/avoid-spa-404/](https://oliverjam.es/blog/avoid-spa-404/)

**Comment by cal-dev-lab** [comment]
Thank you @Alex-Rafter for spotting this. 

Possibly have a solution using react-router-dom and applying a 404 page for all routes that don't match.

**Comment by cal-dev-lab** [comment]
> Urls are returning a 404 e.g https://baunk-agency.netlify.app/category/fashion
> 
> Wondering if this might be due to routing. This could possibly be helpful / might point you in the right direction if it is? https://oliverjam.es/blog/avoid-spa-404/

Hey @Alex-Rafter -- you'll be pleased to know (as well as me) I have managed to add redirects to my project by creating a <code>/public/_redirects</code> file that redirects the user to the <code>PageNotFound<code> component.

Fix found here:
https://github.com/cal-dev-lab/baunk-agency-reactjs/blob/main/public/_redirects

Only problem when sharing a category, it will redirect to PNF as technically this route does not exist as it is created dynamically from mapping through the categories and adding the slug after.

Thanks again for spotting this issue and now any routes that do not exist redirect to <code>/index.html</code>

👍

**Comment by cal-dev-lab** [comment]
@Alex-Rafter I managed to add <code>200</code> to <code>_redirects</code> file which lets the user navigate to categories now along with refreshing the <code>/category/fashion</code> directories.

I believe this is to do with Netlify's setup but this is now fixed 👍
